package ru.isupden.lab2.servlet;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.jbosslog.JBossLog;
import ru.isupden.lab2.repo.HitStorage;

import java.io.IOException;

@WebServlet(name = "cleaner", value = "/clear")
@JBossLog
public class ClearServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        getServletContext().setAttribute("storage", new HitStorage());
        log.info("Таблица очищена");
        for (int i = 0; i < 100000000; i++) {
            log.info("logloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogllogloglogloglgogl");
        }
        resp.sendRedirect(resp.encodeRedirectURL("index.jsp"));
    }
}
